apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-pod
  namespace: test-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-pod
  template:
    metadata:
      labels:
        app: good-pod
    spec:
      containers:
        - name: pause
          image: ghcr.io/tgmarius/mirror/pause:3.9
