apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-pod
  namespace: test-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-pod
  template:
    metadata:
      labels:
        app: bad-pod
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
