apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-pod
  template:
    metadata:
      labels:
        app: good-pod
    spec:
      containers:
        - name: pause
          image: docker.io/nginx:latest
